spring:
  application:
    name: beershop
  datasource:
    url: jdbc:h2:mem:beershopdb
    driver-class-name: org.h2.Driver
  flyway.locations: classpath:/db/migration/{vendor}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false

